name: tezqu
description: "TezQu"
publish_to: 'none'
version: 1.4.0+12
environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  go_router: ^16.2.0
  bloc: ^9.0.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  injectable: ^2.5.1
  iconify_flutter: ^0.0.7
  flutter_screenutil: ^5.9.3
  pin_code_fields: ^8.0.1
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.3.3
  equatable: ^2.0.7
  dartz: ^0.10.1
  connectivity_plus: ^6.1.1
  flutter_dotenv: ^5.2.1
  intl: ^0.20.0
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1
  image_picker: ^1.0.7
  share_plus: ^10.1.2
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.5
  flutter_local_notifications: ^18.0.1
  firebase_remote_config: ^5.1.5
  package_info_plus: ^8.1.2
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.7.0
  freezed: ^3.2.0
  json_serializable: ^6.11.0
  injectable_generator: ^2.8.1
  flutter_launcher_icons: ^0.14.1


flutter:
  assets:
    - assets/images/
    - assets/icons/
    - .env
  uses-material-design: true
  fonts:
    - family: SFCompact
      fonts:
        - asset: assets/fonts/SF_Compact_Display_Regular.ttf
        - asset: assets/fonts/SF_Compact_Display_Medium.ttf
          weight: 500
        - asset: assets/fonts/SF_Compact_Display_Bold.ttf
          weight: 700
        - asset: assets/fonts/SF_Compact_Text_Light.ttf
          weight: 300

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "ios/Runner/Assets.xcassets/AppIcon.appiconset/1024.png"
  remove_alpha_ios: true
